function [ f ] = create_poly_dist( line_segments )
%DERIVATIVE_OF_DISTANCE_TO_POLYGON Returns a function to give you the
%squared distance to a polygon 
% Pass in a shape generated by regular_ngon to retrieve its distance
% function.
    
    f = @distance_to_polygon;
    
    function [ distance_squared ] = distance_to_polygon(point)
        %DISTANCE_TO_POLYGON Returns the squared distance to a polygon from
        %a point.
        
        distances = arrayfun(@(i) distance_to_segment_sq(point, line_segments(:, i)), 1:size(line_segments, 2));
        distance_squared = min(distances);
    end
end

